# Labels analysis

The labels from TransTVDiag are more imbalanced than the labels from TVDiag.

In [2]:
import numpy as np
import pandas as pd

In [3]:
tvdiag_labels_df = pd.read_csv('data/gaia/gaia.csv')
tvdiag_labels_df.head()

,index,datetime,service,instance,message,level,anomaly_type,st_time,ed_time,duration,data_type
0,0,2021-07-04,mobservice,mobservice1,"2021-07-04 00:37:11,553 | WARNING | 0.0.0.1 | ...",WARNING,[login failure],2021-07-04 00:37:11.553000,2021-07-04 00:37:22.553000,11,train
1,1,2021-07-04,mobservice,mobservice2,"2021-07-04 00:48:32,796 | WARNING | 0.0.0.4 | ...",WARNING,[memory_anomalies],2021-07-04 00:38:14.418677,2021-07-04 00:48:14.418677,600,train
2,2,2021-07-04,logservice,logservice1,"2021-07-04 00:59:41,249 | WARNING | 0.0.0.3 | ...",WARNING,[memory_anomalies],2021-07-04 00:49:40.287601,2021-07-04 00:59:40.287601,600,train
3,3,2021-07-04,webservice,webservice2,"2021-07-04 01:10:00,821 | WARNING | 0.0.0.3 | ...",WARNING,[file moving program],2021-07-04 01:00:00.639653,2021-07-04 01:10:00.639653,600,train
4,4,2021-07-04,dbservice,dbservice2,"2021-07-04 01:44:18,107 | WARNING | 0.0.0.2 | ...",WARNING,[memory_anomalies],2021-07-04 01:34:17.188897,2021-07-04 01:44:17.188897,600,train

In [12]:
print(tvdiag_labels_df[tvdiag_labels_df['data_type'] == 'train'].shape)
print(tvdiag_labels_df[tvdiag_labels_df['data_type'] == 'test'].shape)
print(tvdiag_labels_df[tvdiag_labels_df['data_type'] == 'train'].shape[0]/tvdiag_labels_df.shape[0])

(160, 11)
(939, 11)
0.14558689717925385

In [7]:
def value_counts_with_percentages(series, dropna=False, decimals=2):
    counts = series.value_counts(dropna=dropna)
    percents = (series.value_counts(normalize=True, dropna=dropna) * 100).round(decimals)
    return pd.DataFrame({
        'count': counts,
        'percent': percents
    })
# tvdiag_labels_df['anomaly_type'].value_counts()
value_counts_with_percentages(tvdiag_labels_df['anomaly_type'])

                                      count  percent
anomaly_type
[login failure]                         527    47.95
[memory_anomalies]                      505    45.95
[file moving program]                    36     3.28
[normal memory freed label]              16     1.46
[access permission denied exception]     15     1.36

In [14]:
value_counts_with_percentages(tvdiag_labels_df['instance'])

               count  percent
instance
mobservice2      324    29.48
mobservice1      309    28.12
webservice1       76     6.92
dbservice2        75     6.82
webservice2       72     6.55
dbservice1        57     5.19
logservice1       54     4.91
logservice2       49     4.46
redisservice2     48     4.37
redisservice1     35     3.18

In [6]:
transtvdiag_labels_df = pd.read_csv('data/gaia/label_15_85.csv')
transtvdiag_labels_df.head()

,index,datetime,service,instance,message,level,anomaly_type,st_time,ed_time,duration,data_type
0,5,2021-07-01,webservice,webservice2,"2021-07-01 11:16:52,953 | WARNING | 0.0.0.3 | ...",WARNING,[memory_anomalies],2021-07-01 11:06:52.953000,2021-07-01 11:16:52.953000,600,train
1,0,2021-07-01,dbservice,dbservice1,"2021-07-01 11:54:27,616 | WARNING | 0.0.0.4 | ...",WARNING,[memory_anomalies],2021-07-01 11:44:27.616000,2021-07-01 11:54:27.616000,600,train
2,1,2021-07-01,dbservice,dbservice1,"2021-07-01 12:25:08,804 | WARNING | 0.0.0.4 | ...",WARNING,[normal memory freed label],2021-07-01 12:25:08.804000,2021-07-01 12:35:08.804000,600,train
3,3,2021-07-01,dbservice,dbservice2,"2021-07-01 12:54:56,480 | WARNING | 0.0.0.2 | ...",WARNING,[memory_anomalies],2021-07-01 12:44:56.480000,2021-07-01 12:54:56.480000,600,train
4,7,2021-07-01,redisservice,redisservice1,"2021-07-01 13:18:43,143 | WARNING | 0.0.0.1 | ...",WARNING,[memory_anomalies],2021-07-01 13:08:43.143000,2021-07-01 13:18:43.143000,600,train

In [10]:
value_counts_with_percentages(transtvdiag_labels_df['anomaly_type'])

                                      count  percent
anomaly_type
[login failure]                       15478    95.51
[memory_anomalies]                      652     4.02
[file moving program]                    43     0.27
[normal memory freed label]              17     0.10
[access permission denied exception]     15     0.09

In [13]:
value_counts_with_percentages(transtvdiag_labels_df['instance'])

               count  percent
instance
mobservice1     7816    48.23
mobservice2     7796    48.11
dbservice2        96     0.59
webservice2       88     0.54
webservice1       86     0.53
dbservice1        78     0.48
logservice1       67     0.41
logservice2       64     0.39
redisservice2     58     0.36
redisservice1     56     0.35

In [10]:
print(transtvdiag_labels_df[transtvdiag_labels_df['data_type'] == 'train'].shape)
print(transtvdiag_labels_df[transtvdiag_labels_df['data_type'] == 'test'].shape)
print(transtvdiag_labels_df[transtvdiag_labels_df['data_type'] == 'train'].shape[0]/transtvdiag_labels_df.shape[0])

(2431, 11)
(13774, 11)
0.1500154273372416

In [8]:
transtvdiag_labels_df['data_type'].value_counts()

data_type
test     13774
train     2431
Name: count, dtype: int64