In [1]:
import numpy as np
import pandas as pd

In [5]:
tvdiag_labels_df = pd.read_csv('data/gaia/gaia.csv')
tvdiag_labels_df.head()

,index,datetime,service,instance,message,level,anomaly_type,st_time,ed_time,duration,data_type
0,0,2021-07-04,mobservice,mobservice1,"2021-07-04 00:37:11,553 | WARNING | 0.0.0.1 | ...",WARNING,[login failure],2021-07-04 00:37:11.553000,2021-07-04 00:37:22.553000,11,train
1,1,2021-07-04,mobservice,mobservice2,"2021-07-04 00:48:32,796 | WARNING | 0.0.0.4 | ...",WARNING,[memory_anomalies],2021-07-04 00:38:14.418677,2021-07-04 00:48:14.418677,600,train
2,2,2021-07-04,logservice,logservice1,"2021-07-04 00:59:41,249 | WARNING | 0.0.0.3 | ...",WARNING,[memory_anomalies],2021-07-04 00:49:40.287601,2021-07-04 00:59:40.287601,600,train
3,3,2021-07-04,webservice,webservice2,"2021-07-04 01:10:00,821 | WARNING | 0.0.0.3 | ...",WARNING,[file moving program],2021-07-04 01:00:00.639653,2021-07-04 01:10:00.639653,600,train
4,4,2021-07-04,dbservice,dbservice2,"2021-07-04 01:44:18,107 | WARNING | 0.0.0.2 | ...",WARNING,[memory_anomalies],2021-07-04 01:34:17.188897,2021-07-04 01:44:17.188897,600,train

In [6]:
tvdiag_labels_df['anomaly_type'].value_counts()

anomaly_type
[login failure]                         527
[memory_anomalies]                      505
[file moving program]                    36
[normal memory freed label]              16
[access permission denied exception]     15
Name: count, dtype: int64

In [7]:
tvdiag_labels_df['service'].value_counts()

service
mobservice      633
webservice      148
dbservice       132
logservice      103
redisservice     83
Name: count, dtype: int64

In [8]:
transtvdiag_labels_df = pd.read_csv('data/gaia/label_15_85.csv')
transtvdiag_labels_df.head()

,index,datetime,service,instance,message,level,anomaly_type,st_time,ed_time,duration,data_type
0,5,2021-07-01,webservice,webservice2,"2021-07-01 11:16:52,953 | WARNING | 0.0.0.3 | ...",WARNING,[memory_anomalies],2021-07-01 11:06:52.953000,2021-07-01 11:16:52.953000,600,train
1,0,2021-07-01,dbservice,dbservice1,"2021-07-01 11:54:27,616 | WARNING | 0.0.0.4 | ...",WARNING,[memory_anomalies],2021-07-01 11:44:27.616000,2021-07-01 11:54:27.616000,600,train
2,1,2021-07-01,dbservice,dbservice1,"2021-07-01 12:25:08,804 | WARNING | 0.0.0.4 | ...",WARNING,[normal memory freed label],2021-07-01 12:25:08.804000,2021-07-01 12:35:08.804000,600,train
3,3,2021-07-01,dbservice,dbservice2,"2021-07-01 12:54:56,480 | WARNING | 0.0.0.2 | ...",WARNING,[memory_anomalies],2021-07-01 12:44:56.480000,2021-07-01 12:54:56.480000,600,train
4,7,2021-07-01,redisservice,redisservice1,"2021-07-01 13:18:43,143 | WARNING | 0.0.0.1 | ...",WARNING,[memory_anomalies],2021-07-01 13:08:43.143000,2021-07-01 13:18:43.143000,600,train

In [9]:
transtvdiag_labels_df['anomaly_type'].value_counts()

anomaly_type
[login failure]                         15478
[memory_anomalies]                        652
[file moving program]                      43
[normal memory freed label]                17
[access permission denied exception]       15
Name: count, dtype: int64

In [10]:
transtvdiag_labels_df['service'].value_counts()

service
mobservice      15612
webservice        174
dbservice         174
logservice        131
redisservice      114
Name: count, dtype: int64