In [2]:
import pandas as pd
import numpy as np

In [3]:
full_labels_df = pd.read_csv('label_15_85.csv')
full_labels_df.head()
full_labels_df.shape

(16205, 11)

In [6]:

df = pd.read_csv("label_15_85.csv")

check = df[['index']].copy()
check['df_index'] = df.index
check = check[['df_index', 'index']]

check.head(20)

    df_index  index
0          0      5
1          1      0
2          2      1
3          3      3
4          4      7
5          5      4
6          6     14
7          7    113
8          8     15
9          9     16
10        10    114
11        11    115
12        12    116
13        13     17
14        14    117
15        15    118
16        16     18
17        17    119
18        18    120
19        19     19

In [8]:
range(len(full_labels_df))

range(0, 16205)

In [9]:
full_labels_new_index_df = full_labels_df.copy()
full_labels_new_index_df['old_index'] = full_labels_new_index_df['index']
full_labels_new_index_df['index'] = range(len(full_labels_new_index_df))
full_labels_new_index_df

,index,datetime,service,instance,message,level,anomaly_type,st_time,ed_time,duration,data_type,old_index
0,0,2021-07-01,webservice,webservice2,"2021-07-01 11:16:52,953 | WARNING | 0.0.0.3 | ...",WARNING,[memory_anomalies],2021-07-01 11:06:52.953000,2021-07-01 11:16:52.953000,600,train,5
1,1,2021-07-01,dbservice,dbservice1,"2021-07-01 11:54:27,616 | WARNING | 0.0.0.4 | ...",WARNING,[memory_anomalies],2021-07-01 11:44:27.616000,2021-07-01 11:54:27.616000,600,train,0
2,2,2021-07-01,dbservice,dbservice1,"2021-07-01 12:25:08,804 | WARNING | 0.0.0.4 | ...",WARNING,[normal memory freed label],2021-07-01 12:25:08.804000,2021-07-01 12:35:08.804000,600,train,1
3,3,2021-07-01,dbservice,dbservice2,"2021-07-01 12:54:56,480 | WARNING | 0.0.0.2 | ...",WARNING,[memory_anomalies],2021-07-01 12:44:56.480000,2021-07-01 12:54:56.480000,600,train,3
4,4,2021-07-01,redisservice,redisservice1,"2021-07-01 13:18:43,143 | WARNING | 0.0.0.1 | ...",WARNING,[memory_anomalies],2021-07-01 13:08:43.143000,2021-07-01 13:18:43.143000,600,train,7
...,...,...,...,...,...,...,...,...,...,...,...,...
16200,16200,2021-07-31,mobservice,mobservice2,"2021-07-31 23:47:41,157 | WARNING | 0.0.0.4 | ...",WARNING,[login failure],2021-07-31 23:47:41.157000,2021-07-31 23:47:52.157000,11,test,15828
16201,16201,2021-07-31,mobservice,mobservice1,"2021-07-31 23:54:35,145 | WARNING | 0.0.0.1 | ...",WARNING,[login failure],2021-07-31 23:54:35.145000,2021-07-31 23:54:46.145000,11,test,16190
16202,16202,2021-07-31,mobservice,mobservice1,"2021-07-31 23:54:49,585 | WARNING | 0.0.0.1 | ...",WARNING,[login failure],2021-07-31 23:54:49.585000,2021-07-31 23:55:00.585000,11,test,16191
16203,16203,2021-07-31,mobservice,mobservice2,"2021-07-31 23:59:14,048 | WARNING | 0.0.0.4 | ...",WARNING,[login failure],2021-07-31 23:59:14.048000,2021-07-31 23:59:25.048000,11,test,15829
16204,16204,2021-07-31,mobservice,mobservice1,"2021-07-31 23:59:41,313 | WARNING | 0.0.0.1 | ...",WARNING,[login failure],2021-07-31 23:59:41.313000,2021-07-31 23:59:52.313000,11,test,16192

In [10]:
full_labels_new_index_df.to_csv('label_15_85_corrected_index.csv', index=False)

In [17]:
labels_without_login_failure_df = full_labels_df[
    full_labels_df['anomaly_type'] != '[login failure]'
]
labels_without_login_failure_df.shape

(727, 11)

In [7]:
full_labels_df.shape

(16205, 11)

In [18]:
print(labels_without_login_failure_df[labels_without_login_failure_df['data_type'] == 'train'].shape)
print(labels_without_login_failure_df[labels_without_login_failure_df['data_type'] == 'test'].shape)

(96, 11)
(631, 11)

In [19]:
labels_without_login_failure_df.to_csv('labels_without_login.csv', index=False)

In [16]:
full_labels_df['anomaly_type'].unique()

array(['[memory_anomalies]', '[normal memory freed label]',
       '[login failure]', '[file moving program]',
       '[access permission denied exception]'], dtype=object)

In [20]:
def value_counts_with_percentages(series, dropna=False, decimals=2):
    counts = series.value_counts(dropna=dropna)
    percents = (series.value_counts(normalize=True, dropna=dropna) * 100).round(decimals)
    return pd.DataFrame({
        'count': counts,
        'percent': percents
    })
# tvdiag_labels_df['anomaly_type'].value_counts()
value_counts_with_percentages(labels_without_login_failure_df['anomaly_type'])

                                      count  percent
anomaly_type
[memory_anomalies]                      652    89.68
[file moving program]                    43     5.91
[normal memory freed label]              17     2.34
[access permission denied exception]     15     2.06

In [21]:
print('Train labels distribution without login failure')
value_counts_with_percentages(labels_without_login_failure_df[labels_without_login_failure_df['data_type'] == 'train']['anomaly_type'])

                             count  percent
anomaly_type
[memory_anomalies]              88    91.67
[file moving program]            6     6.25
[normal memory freed label]      2     2.08

In [23]:
print('Test labels distribution without login failure')
value_counts_with_percentages(labels_without_login_failure_df[labels_without_login_failure_df['data_type'] == 'test']['anomaly_type'])

Test labels distribution without login failure

                                      count  percent
anomaly_type
[memory_anomalies]                      564    89.38
[file moving program]                    37     5.86
[normal memory freed label]              15     2.38
[access permission denied exception]     15     2.38

In [24]:
print('Train labels distribution for full dataset')
value_counts_with_percentages(full_labels_df[full_labels_df['data_type'] == 'train']['anomaly_type'])

Train labels distribution for full dataset

                             count  percent
anomaly_type
[login failure]               2335    96.05
[memory_anomalies]              88     3.62
[file moving program]            6     0.25
[normal memory freed label]      2     0.08

In [25]:
print('Test labels distribution for full dataset')
value_counts_with_percentages(full_labels_df[full_labels_df['data_type'] == 'test']['anomaly_type'])

Test labels distribution for full dataset

                                      count  percent
anomaly_type
[login failure]                       13143    95.42
[memory_anomalies]                      564     4.09
[file moving program]                    37     0.27
[normal memory freed label]              15     0.11
[access permission denied exception]     15     0.11